[project]
name = "moderation-text-toxicornotclassifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gensim>=4.4.0",
    "joblib>=1.5.3",
    "numpy>=2.2.6",
    "pika>=1.3.2",
    "pydantic>=2.12.5",
]
